### ISSUE TITLE
Bug with elapsed time

### ISSUE THREAD

**Issue by Klemmbaustein** [R2Northstar/NorthstarDiscordRPC#9]
When the game is launched, the elapsed time will be around 17 hours, before it's reset to 0 when finally loading into the main menu.

**Comment by ASpoonPlaysGames** [comment]
I also have this issue

**Comment by catornot** [comment]
yeah, it doesn't overwrite everything when the activity starts so stuff might be carried over from previous activities ig
https://github.com/R2Northstar/NorthstarDiscordRPC/blob/46d073ae37472a61aee44dfea4fe10440dd4f1ac/src/lib.rs#L50

**Comment by GeckoEidechse** [comment]
Shouldn't the fix be as "simple" as just sending zeroes for initial data?

**Comment by GeckoEidechse** [comment]
Apparently this is fixed in v3 according to @catornot

**Comment by catornot** [comment]
should be fixed by https://github.com/R2Northstar/NorthstarDiscordRPC/pull/10
